title: Gabriel Florio # your name (or website title) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  My personal webpage
  <br>
  <a href="/curriculum">Curriculum Vitæ</a>
  <br>
  <a href="https://www.linkedin.com/in/gabriel-florio-a5227211a">LinkedIn Profile</a> 
  
theme: jekyll-theme-dinky
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
