title: Gabriel Florio
description: Personal page and blog
author: Gabriel Florio
theme: jekyll-theme-dinky
google_analytics: UA-162263021-1
url: https://www.gabrielflorio.com

plugins:
  - jekyll-feed
  - jekyll-paginate

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true

paginate: 5

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
